#!/usr/bin/python

"""

 ssh-jump: 'netcat' that finds a nova instance, and jumps
 into its namespace.

"""

import traceback, sys

import os, sys
import prctl
import shlex
import find_ns
from datetime import datetime

if (len(sys.argv) == 1):
    sys.argv.extend(shlex.split(sys.stdin.readline()))

args = find_ns.do_args()

try:
    # This allows our app to get into a network namespace other than the default.
    # to do so, open /var/run/netns/<file>, and then have @ it with the fd using
    # the setns(2) call. E.g. f=open('/var/run/netns/x'); setns(f)
    prctl.cap_permitted.sys_admin = True
    prctl.cap_effective.sys_admin = True

    h, ns,floating = find_ns.find_host(args.user, args.tenant, args.password, args.host, args.auth_url, args.shared_subnet_id, args.shared_router_id)

    if (args.test):
        # In this case, we want to just check that namespace is up
        print >> sys.stderr, ("Testing primary routed interface/router for host <<%s>> in tenant <<%s>>" % (args.host,args.tenant))
        print >> sys.stderr, (" Routed Namespace: <<%s>>, ip: <<%s>>" % (ns, h))
        if (h == None or ns == None):
            print >> sys.stderr, (" Error: one of host/routed-namespace is empty")
            sys.exit(1)
        try:
            _ns = find_ns.NS(ns)
        except:
            print >> sys.stderr, (" Error: router <<%s>> does not exist (yet)" % ns)
            sys.exit(1)
        else:
            # Now we should be able to ping h
            os.execv('/bin/ping',['/bin/ping', '-q','-c','1', h])
    elif (len(ns)):
        _ns = find_ns.NS(ns)
        os.execv('/bin/nc',['/bin/nc', h, '22'])
except:
    if (not args.test):
        dt = datetime.now()
        print("TIMESTAMP: %s" % dt.isoformat("T"))

        traceback.print_exc()
        print >> sys.stderr, ("Usage: -user <USER> -password <PASSWORD> -tenant <TENANT> -host <HOST>")
        print >> sys.stderr, ("where USER/PASSWORD/TENANT/HOST are all as per this OpenStack deployment")
        print >> sys.stderr, ("and may not be a Unix login")
        print >> sys.stderr, ("You gave: <<%s>>" % sys.argv)
    sys.exit(1)
